# pnpm workspace configuration
# apps/: Applications (API, Worker, Planner, Judge, Dispatcher)
# packages/: Shared packages (core, db, llm, vcs, queue, policies)
packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*"
