import { createPR, findPRs, updatePR, type PRInfo } from "@h1ve/vcs";
import type { Task } from "@h1ve/core";

export interface CreatePROptions {
  branchName: string;
  task: Task;
  baseBranch?: string;
  changedFiles: string[];
  stats: { additions: number; deletions: number };
  verificationResults: Array<{ command: string; success: boolean }>;
}

export interface CreatePRResult {
  success: boolean;
  pr?: PRInfo;
  isUpdate?: boolean;
  error?: string;
}

// PR本文を生成
function generatePRBody(options: CreatePROptions): string {
  const { task, changedFiles, stats, verificationResults } = options;

  const lines: string[] = [
    "## Summary",
    "",
    task.goal,
    "",
  ];

  // タスク情報
  lines.push(
    "## Task Details",
    "",
    `- **Task ID**: \`${task.id}\``,
    `- **Risk Level**: ${task.riskLevel}`,
    `- **Timebox**: ${task.timeboxMinutes} minutes`,
    ""
  );

  // 変更統計
  lines.push(
    "## Changes",
    "",
    `**${changedFiles.length}** files changed, **${stats.additions}** insertions(+), **${stats.deletions}** deletions(-)`,
    ""
  );

  // 変更ファイル一覧
  if (changedFiles.length > 0) {
    lines.push("<details>", "<summary>Changed files</summary>", "");
    for (const file of changedFiles) {
      lines.push(`- \`${file}\``);
    }
    lines.push("", "</details>", "");
  }

  // 検証結果
  lines.push("## Verification", "");
  for (const result of verificationResults) {
    const icon = result.success ? "✅" : "❌";
    lines.push(`${icon} \`${result.command}\``);
  }
  lines.push("");

  // 自動生成ラベル
  lines.push(
    "---",
    "",
    "_This PR was automatically generated by h1ve._",
    "",
    `Labels: \`agent\`, \`${task.riskLevel}-risk\``
  );

  return lines.join("\n");
}

// PRを作成または更新
export async function createTaskPR(
  options: CreatePROptions
): Promise<CreatePRResult> {
  const { branchName, task, baseBranch = "main" } = options;

  console.log("Checking for existing PR...");

  const title = `[h1ve] ${task.title}`;
  const body = generatePRBody(options);

  // リスクレベルに応じたラベル
  const labels = ["agent", "autogen", `${task.riskLevel}-risk`];

  try {
    // 既存のPRを探す（同じブランチからのPR）
    const existingPRs = await findPRs({
      head: branchName,
      base: baseBranch,
      state: "open",
    });

    if (existingPRs.length > 0 && existingPRs[0]) {
      const existingPR = existingPRs[0];
      console.log(`Updating existing PR #${existingPR.number}...`);

      const pr = await updatePR(existingPR.number, {
        title,
        body,
        labels,
      });

      return {
        success: true,
        pr,
        isUpdate: true,
      };
    }

    console.log("Creating new PR...");
    const pr = await createPR({
      title,
      body,
      head: branchName,
      base: baseBranch,
      labels,
      draft: task.riskLevel === "high", // 高リスクはdraftで作成
    });

    console.log(`PR created: ${pr.url}`);

    return {
      success: true,
      pr,
      isUpdate: false,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("Failed to create/update PR:", message);

    return {
      success: false,
      error: message,
    };
  }
}
